services:
  db:
    image: postgres:16
    container_name: endangered_ocean_db
    environment:
      POSTGRES_DB: ocean_db
      POSTGRES_USER: ocean
      POSTGRES_PASSWORD: ocean
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ocean -d ocean_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
